"""baseline schema

Revision ID: faa9c956fcbe
Revises:
Create Date: 2025-11-03 21:24:00.550296

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "faa9c956fcbe"
down_revision: tuple[str, ...] | str | None = None
branch_labels: tuple[str, ...] | str | None = None
depends_on: tuple[str, ...] | str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sort_name", sa.String(), nullable=True),
        sa.Column("country", sa.String(length=3), nullable=True),
        sa.Column("formed_year", sa.Integer(), nullable=True),
        sa.Column("disbanded_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artist")),
    )
    op.create_table(
        "entity_merge",
        sa.Column(
            "entity_type",
            sa.Enum(
                "ARTIST",
                "RELEASE_SET",
                "RELEASE",
                "RECORDING",
                "TRACK",
                "LABEL",
                name="canonicalentitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason", sa.Enum("MANUAL", name="mergereason", native_enum=False), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "entity_type", "source_id", "target_id", name=op.f("pk_entity_merge")
        ),
    )
    op.create_table(
        "external_id",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "ARTIST",
                "RELEASE_SET",
                "RELEASE",
                "RECORDING",
                "TRACK",
                "LABEL",
                name="canonicalentitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("LASTFM", "SPOTIFY", "MUSICBRAINZ", name="provider", native_enum=False),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_id")),
        sa.UniqueConstraint(
            "namespace", "value", "entity_type", name=op.f("uq_external_id_external_id_namespace")
        ),
    )
    op.create_table(
        "label",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label")),
    )
    op.create_table(
        "recording",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recording")),
    )
    op.create_table(
        "release_set",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "primary_type",
            sa.Enum(
                "ALBUM",
                "SINGLE",
                "EP",
                "LIVE",
                "COMPILATION",
                "SOUNDTRACK",
                "MIXTAPE",
                "OTHER",
                name="releasesettype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("first_release_year", sa.Integer(), nullable=True),
        sa.Column("first_release_month", sa.Integer(), nullable=True),
        sa.Column("first_release_day", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_set")),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("spotify_user_id", sa.String(), nullable=True),
        sa.Column("lastfm_user", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
    )
    op.create_table(
        "library_item",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "ARTIST",
                "RELEASE_SET",
                "RELEASE",
                "RECORDING",
                "TRACK",
                "LABEL",
                name="canonicalentitytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("LASTFM", "SPOTIFY", "MUSICBRAINZ", name="provider", native_enum=False),
            nullable=True,
        ),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_library_item_library_item_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_library_item")),
        sa.UniqueConstraint("user_id", "entity_type", "entity_id", name="uq_library_item_entity"),
    )
    op.create_table(
        "recording_artist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recording_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("instrument", sa.String(), nullable=True),
        sa.Column("credit_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name=op.f("fk_recording_artist_recording_artist_artist_id_artist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
            name=op.f("fk_recording_artist_recording_artist_recording_id_recording"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recording_artist")),
    )
    op.create_table(
        "release",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("release_set_id", sa.Uuid(), nullable=False),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("release_month", sa.Integer(), nullable=True),
        sa.Column("release_day", sa.Integer(), nullable=True),
        sa.Column("country", sa.String(length=3), nullable=True),
        sa.Column("format", sa.String(), nullable=True),
        sa.Column("medium_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_set_id"],
            ["release_set.id"],
            name=op.f("fk_release_release_release_set_id_release_set"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release")),
    )
    op.create_table(
        "release_set_artist",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("release_set_id", sa.Uuid(), nullable=False),
        sa.Column("artist_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("credit_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artist.id"],
            name=op.f("fk_release_set_artist_release_set_artist_artist_id_artist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_set_id"],
            ["release_set.id"],
            name=op.f("fk_release_set_artist_release_set_artist_release_set_id_release_set"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_set_artist")),
    )
    op.create_table(
        "release_label",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("label_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
            name=op.f("fk_release_label_release_label_label_id_label"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["release.id"],
            name=op.f("fk_release_label_release_label_release_id_release"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("release_id", "label_id", name=op.f("pk_release_label")),
    )
    op.create_table(
        "track",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("recording_id", sa.Uuid(), nullable=False),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("title_override", sa.String(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"], ["recording.id"], name=op.f("fk_track_track_recording_id_recording")
        ),
        sa.ForeignKeyConstraint(
            ["release_id"], ["release.id"], name=op.f("fk_track_track_release_id_release")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track")),
    )
    op.create_table(
        "play_event",
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload_id", sa.Uuid(), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("LASTFM", "SPOTIFY", "MUSICBRAINZ", name="provider", native_enum=False),
            nullable=False,
        ),
        sa.Column("recording_id", sa.Uuid(), nullable=False),
        sa.Column("track_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recording_id"],
            ["recording.id"],
            name=op.f("fk_play_event_play_event_recording_id_recording"),
        ),
        sa.ForeignKeyConstraint(
            ["track_id"], ["track.id"], name=op.f("fk_play_event_play_event_track_id_track")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_play_event_play_event_user_id_user_account"),
        ),
        sa.PrimaryKeyConstraint("played_at", name=op.f("pk_play_event")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("play_event")
    op.drop_table("track")
    op.drop_table("release_label")
    op.drop_table("release_set_artist")
    op.drop_table("release")
    op.drop_table("recording_artist")
    op.drop_table("library_item")
    op.drop_table("user_account")
    op.drop_table("release_set")
    op.drop_table("recording")
    op.drop_table("label")
    op.drop_table("external_id")
    op.drop_table("entity_merge")
    op.drop_table("artist")
    # ### end Alembic commands ###
