"""Generic reconciliation core for integrating claim graphs into the catalog."""

from __future__ import annotations

from .apply import ApplyCounters, ApplyResult
from .claims import (
    AnyRelationshipClaim,
    AssociationClaim,
    AssociationKind,
    ClaimEvidence,
    ClaimMetadata,
    EntityClaim,
    LinkClaim,
    LinkKind,
    RelationshipKind,
    UserEntity,
)
from .contracts import (
    AmbiguousResolution,
    ApplyStrategy,
    AssociationApplyInstruction,
    AssociationInstructionsByClaim,
    AssociationResolution,
    AssociationResolutionsByClaim,
    BlockedResolution,
    ClaimKey,
    ConflictResolution,
    CreateInstruction,
    EntityApplyInstruction,
    EntityInstructionsByClaim,
    EntityResolution,
    EntityResolutionsByClaim,
    KeysByClaim,
    LinkApplyInstruction,
    LinkConflictResolution,
    LinkCreateInstruction,
    LinkInstructionsByClaim,
    LinkManualReviewInstruction,
    LinkNoopInstruction,
    LinkResolution,
    LinkResolutionsByClaim,
    LinkResolvedResolution,
    ManualReviewInstruction,
    ManualReviewItem,
    ManualReviewSubject,
    MatchKind,
    MergeInstruction,
    NewResolution,
    NoopInstruction,
    Representative,
    RepresentativesByClaim,
    ResolutionStatus,
    ResolvedResolution,
)
from .engine import ExecutedReconciliation, PreparedReconciliation, ReconciliationEngine
from .graph import ClaimGraph

__all__ = [
    "AmbiguousResolution",
    "AnyRelationshipClaim",
    "ApplyCounters",
    "ApplyResult",
    "ApplyStrategy",
    "AssociationApplyInstruction",
    "AssociationClaim",
    "AssociationInstructionsByClaim",
    "AssociationKind",
    "AssociationResolution",
    "AssociationResolutionsByClaim",
    "BlockedResolution",
    "ClaimEvidence",
    "ClaimGraph",
    "ClaimKey",
    "ClaimMetadata",
    "ConflictResolution",
    "CreateInstruction",
    "EntityApplyInstruction",
    "EntityClaim",
    "EntityInstructionsByClaim",
    "EntityResolution",
    "EntityResolutionsByClaim",
    "ExecutedReconciliation",
    "KeysByClaim",
    "LinkApplyInstruction",
    "LinkClaim",
    "LinkConflictResolution",
    "LinkCreateInstruction",
    "LinkInstructionsByClaim",
    "LinkKind",
    "LinkManualReviewInstruction",
    "LinkNoopInstruction",
    "LinkResolution",
    "LinkResolutionsByClaim",
    "LinkResolvedResolution",
    "ManualReviewInstruction",
    "ManualReviewItem",
    "ManualReviewSubject",
    "MatchKind",
    "MergeInstruction",
    "NewResolution",
    "NoopInstruction",
    "PreparedReconciliation",
    "ReconciliationEngine",
    "RelationshipKind",
    "Representative",
    "RepresentativesByClaim",
    "ResolutionStatus",
    "ResolvedResolution",
    "UserEntity",
]
