"""Reconciliation core for integrating external claim graphs into the catalog."""

from __future__ import annotations

from .apply import ApplyCounters, ApplyResult
from .catalog import CatalogClaimGraphBundle, build_catalog_claim_graph
from .claims import (
    AnyRelationshipClaim,
    AssociationClaim,
    AssociationKind,
    ClaimEvidence,
    ClaimMetadata,
    EntityClaim,
    LinkClaim,
    LinkKind,
    RelationshipKind,
    UserEntity,
)
from .contracts import (
    AmbiguousResolution,
    ApplyStrategy,
    AssociationApplyInstruction,
    AssociationInstructionsByClaim,
    AssociationResolution,
    AssociationResolutionsByClaim,
    BlockedResolution,
    ClaimKey,
    ConflictResolution,
    CreateInstruction,
    EntityApplyInstruction,
    EntityInstructionsByClaim,
    EntityResolution,
    EntityResolutionsByClaim,
    KeysByClaim,
    LinkApplyInstruction,
    LinkConflictResolution,
    LinkCreateInstruction,
    LinkInstructionsByClaim,
    LinkManualReviewInstruction,
    LinkNoopInstruction,
    LinkResolution,
    LinkResolutionsByClaim,
    LinkResolvedResolution,
    ManualReviewInstruction,
    ManualReviewItem,
    ManualReviewSubject,
    MatchKind,
    MergeInstruction,
    NewResolution,
    NoopInstruction,
    Representative,
    RepresentativesByClaim,
    ResolutionStatus,
    ResolvedResolution,
)
from .factory import create_default_reconciliation_engine
from .graph import ClaimGraph
from .release_candidates import ReleaseSelectionPolicy, resolve_release_candidate
from .workflows import (
    LastfmReconciliationResult,
    LibraryItemReconciliationRequest,
    MusicBrainzReconciliationResult,
    PlayEventReconciliationRequest,
    ReconciliationRunResult,
    SpotifyLibraryReconciliationResult,
    reconcile_library_items,
    reconcile_musicbrainz_releases,
    reconcile_play_events,
)

__all__ = [
    "AmbiguousResolution",
    "AnyRelationshipClaim",
    "ApplyCounters",
    "ApplyResult",
    "ApplyStrategy",
    "AssociationApplyInstruction",
    "AssociationClaim",
    "AssociationInstructionsByClaim",
    "AssociationKind",
    "AssociationResolution",
    "AssociationResolutionsByClaim",
    "BlockedResolution",
    "CatalogClaimGraphBundle",
    "ClaimEvidence",
    "ClaimGraph",
    "ClaimKey",
    "ClaimMetadata",
    "ConflictResolution",
    "CreateInstruction",
    "EntityApplyInstruction",
    "EntityClaim",
    "EntityInstructionsByClaim",
    "EntityResolution",
    "EntityResolutionsByClaim",
    "KeysByClaim",
    "LastfmReconciliationResult",
    "LibraryItemReconciliationRequest",
    "LinkApplyInstruction",
    "LinkClaim",
    "LinkConflictResolution",
    "LinkCreateInstruction",
    "LinkInstructionsByClaim",
    "LinkKind",
    "LinkManualReviewInstruction",
    "LinkNoopInstruction",
    "LinkResolution",
    "LinkResolutionsByClaim",
    "LinkResolvedResolution",
    "ManualReviewInstruction",
    "ManualReviewItem",
    "ManualReviewSubject",
    "MatchKind",
    "MergeInstruction",
    "MusicBrainzReconciliationResult",
    "NewResolution",
    "NoopInstruction",
    "PlayEventReconciliationRequest",
    "ReconciliationRunResult",
    "RelationshipKind",
    "ReleaseSelectionPolicy",
    "Representative",
    "RepresentativesByClaim",
    "ResolutionStatus",
    "ResolvedResolution",
    "SpotifyLibraryReconciliationResult",
    "UserEntity",
    "build_catalog_claim_graph",
    "create_default_reconciliation_engine",
    "reconcile_library_items",
    "reconcile_musicbrainz_releases",
    "reconcile_play_events",
    "resolve_release_candidate",
]
